vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\config.ps1" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\config.ps1" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\AD_verdeling.ps1" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\AD_verdeling.ps1" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\dns.ps1" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\dns.ps1" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\gpo's.ps1" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\gpo's.ps1" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\sharedFolders.ps1" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\sharedFolders.ps1" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\dnsExtra.ps1" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\dnsExtra.ps1" --username "Administrator" --password "23Admin24"
# NOG NIET GETEST
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\A-records.csv" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\csv\A-records.csv" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\CNAME-records.csv" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\csv\CNAME-records.csv" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\gebruikers.csv" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\csv\gebruikers.csv" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\PTR-records.csv" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\csv\PTR-records.csv" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\IPv6-PTR-records.csv" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\csv\IPv6-PTR-records.csv" --username "Administrator" --password "23Admin24"
vboxmanage guestcontrol DomainController copyto --target-directory "C:\Users\Administrator\Downloads\AAAA-records.csv" "C:\Users\peter\OneDrive\Bureaublad\HOGENT\2de\semester2\SEP\sep2324-gent-g03\uitwerking\VMs\Windows\WinServer\csv\AAAA-records.csv" --username "Administrator" --password "23Admin24"

# vboxmanage guestcontrol DomainController run --exe  ...
# -> om bv script automatisch te runnen, kan mss handig zijn voor later

